---
application:
  name: "urml-ml"
  project: "finaltry"
  organization: "QoveryCommunity"
  custom_domains:
  - branch: main
    domain: www.lenk.cf
routers:
- name: "main-urml-ml"
  routes:
  - application_name: "urml-ml"
    paths:
    - "/*"
